export const taglines = [
    "Why not look here after all?",
    "Stop doomscrolling, start jobscrolling!",
    "Optimize your career path—start here!",
    "404: Your perfect job is not found... yet.",
    "Why not train your career model here?",
    "You. AI. Job. It's giving perfect match",
    "Careers but like not corporate",
    "Why let AI take your job when you can take AI jobs?",
    "Apply before your WiFi drops!",
    "Jobs so good, they pass the Turing Test",
    "Work smarter, not harder",
    "You when you find the perfect AI job 😍",
    "Not you finding the perfect job",
    "Let's get this bread…",
    "Step 1: Click. Step 2: ??? Step 3: Profit.",
    "Pause Netflix. Secure the bag",
    "Have a look around",
    "Share it with your friends",
    "Great jobs no 🧢",
    "Treat yourself to a job 💅",
    "Secure the bag bestie 💰",
    "Diamond hands incoming 🙌💎",
];
